project:
  type: website
  output-dir: docs

website:
  title: "Quarto Test"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

editor: visual

